/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef ECS_COLLIDIONG_SHAPES_BAKE_CONFIG_H
#define ECS_COLLIDIONG_SHAPES_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs>
#include <flecs.components.transform>
#include <flecs.components.physics>
#include <flecs.components.geometry>
#include <flecs.components.graphics>
#include <flecs.systems.physics>
#include <flecs.systems.sdl2>
#include <flecs.math>

/* Headers of private dependencies */
#ifdef ECS_COLLIDIONG_SHAPES_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if ECS_COLLIDIONG_SHAPES_IMPL && defined _MSC_VER
#define ECS_COLLIDIONG_SHAPES_EXPORT __declspec(dllexport)
#elif ECS_COLLIDIONG_SHAPES_IMPL
#define ECS_COLLIDIONG_SHAPES_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define ECS_COLLIDIONG_SHAPES_EXPORT __declspec(dllimport)
#else
#define ECS_COLLIDIONG_SHAPES_EXPORT
#endif

#endif

